Add a `wheels-publish` job
rapidsai/pynvjitlink pull request #25
Opened 2023-12-04 20:14 UTC by brandon-b-miller

This PR adds a job to our release workflow which uploads release wheels to the nightly rapids pypi index.

2023-12-04 22:18 UTC, vyasr requested changes

2023-12-04 23:18 UTC, vyasr requested changes

2023-12-04 23:18 UTC, vyasr commented on .github/workflows/build.yaml
> +      build_type: pull-request
The changes we made to get things working in pr.yaml don't apply in build.yaml. You want to undo the changes to this file in https://github.com/rapidsai/pynvjitlink/pull/25/commits/3e1fcf2f27f8eafda1fc8981968acbc6e72b4681

2023-12-04 23:31 UTC, vyasr approved these changes

2023-12-05 14:57 UTC, raydouglass approved these changes

2023-12-05 15:03 UTC, merged