nvjitlink->pynvjitlink
rapidsai/pynvjitlink pull request #5
Opened 2023-07-20 20:07 UTC by brandon-b-miller

This PR renames the library to `pynvjitlink` to avoid confusion with the c++ library.

2023-07-20 20:14 UTC, bdice approved these changes

2023-07-25 00:18 UTC, vyasr requested changes
One small change to make.

2023-07-25 00:18 UTC, vyasr commented on .github/CODEOWNERS
The nvjitlink* teams don't actually exist (and of course neither do the pynvjitlink ones). Can we change all of them in this file to just pynvjitlink-write for now? We can decide at a later date if we really need separate teams for the different components (the package is minimal enough that I don't know if it will be necessary).

I've requested that ops rename the teams accordingly.

2023-07-25 14:07 UTC, brandon-b-miller commented on .github/CODEOWNERS
Done, I left the `.github` folder under ops.

2023-07-25 19:18 UTC, vyasr approved these changes

2023-07-25 20:14 UTC, merged